Added a grep cmd to check for 500 errors

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,5 +20,11 @@ jobs:
         docker run -d -p 5000:5000 python-docker
         sleep 5
         docker ps -a
-        curl --retry 2 http://localhost:5000/
+        if curl -s http://localhost:5000/ | grep -o "500 Internal Server Error"
+          then
+            echo "A 500 Internal server error was reported. Cannot allow PR to merge!"
+            exit 1
+          else
+            echo "Website does not return a 500 error code."
+        fi
 
